### ISSUE TITLE
Extract CWP functionality into this module, or delete module?

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-auditor#1]
@mateusz I think the original purpose of this module was to generalise functionality of cwp.govt.nz, right? I think if we're serious about publishing this auditor functionality under the silverstripe github organisation, we should move the CWP functionality here and make it a supported module.

If we aren't prepared to do that, we should remove the module. It's not registered on packagist.org, so can't have a whole lot of users anyway.

Specifically, I'm talking about these CWP features:
https://gitlab.cwp.govt.nz/cwp/cwp-core/blob/master/code/extensions/CwpSecurity.php
https://gitlab.cwp.govt.nz/cwp/cwp-core/blob/master/code/extensions/LoginAttemptNotifications.php
https://gitlab.cwp.govt.nz/cwp/cwp-core/blob/master/code/CwpLogger.php
https://gitlab.cwp.govt.nz/cwp/cwp-core/blob/master/code/CwpLoggerFormatter.php
https://gitlab.cwp.govt.nz/cwp/cwp-core/blob/master/code/model/CwpLoggerManyManyList.php
https://gitlab.cwp.govt.nz/cwp/cwp-core/blob/master/code/model/CwpLoggerMemberGroupSet.php

**Comment by tractorcow** [comment]
Yes please... it just needs someone willing to put in the work to turn this into "supported module" standard.

**Comment by mateusz** [comment]
Done.
