### ISSUE TITLE
Use traditional array syntax to support PHP>=5.3.2

### ISSUE THREAD

**Issue by fspringveldt** [silverstripe/silverstripe-auditor#10]
MonologueSyslogWriter line 64 breaks cwp/cwp-recipe-basic compatibility due to short array syntax.

**Comment by fspringveldt** [comment]
Not needed as CWP platform runs PHP 5.6

**Comment by robbieaverill** [comment]
We should remove PHP 5.3 from the Travis build matrix in this module though, since it won't work on PHP 5.3 without your fix in #11
