### ISSUE TITLE
Replace manual class creation with injection or extensions

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-auditor#16]
The way that `bind_manipulation_capture()` creates a spy class for the database driver could potentially be improved.

FullTextSearch used the same method in the SS3 version, and has been replaced with Injector overloading, however this won't work for both this module in combination with that module too. See relevant conversation here: https://github.com/silverstripe/silverstripe-fulltextsearch/pull/184

We discussed adding sufficient extension points to `DB::manipulate` so that we wouldn't need this at all, but that may not happen until SS 4.1 if at all.

**Comment by robbieaverill** [comment]
This has become more of a priority now since CWP 2.0 contains the following modules that are all trying to proxy the database connector:

* lekoala/silverstripe-debugbar
* silverstripe/fulltextsearch
* this module

We could create a new module e.g. silverstripe/databaseproxy which could expose event hooks in some cases, and each of these modules could require it. Perhaps a sort of event/subscriber type situation.

cc @tractorcow

**Comment by robbieaverill** [comment]
Removed from 2.0.0 stable milestone for now

**Comment by tractorcow** [comment]
I have a concept in mind for a generic class proxy but we don't have time to do it before 2.0.0.

**Comment by tractorcow** [comment]
Use https://github.com/tractorcow/silverstripe-proxy-db to solve this issue.

Also see:
 - https://github.com/silverstripe/silverstripe-fulltextsearch/issues/201
 - https://github.com/lekoala/silverstripe-debugbar/issues/93
 
 Which can all share this proxy

**Comment by robbieaverill** [comment]
Nice! Added back to milestone

**Comment by robbieaverill** [comment]
PR at #18
