### ISSUE TITLE
PermissionRoleCode changes are not registered via Auditor

### ISSUE THREAD

**Issue by mateusz** [silverstripe/silverstripe-auditor#24]
Replication steps: tick some boxes on a role, save. Notice it's not logged.

It looks like it lacks a `PermissionRoleCode` case in `handle_manipulation` maybe? `handle_manipulation` is for sure triggered (at least on 3.7) and the $table is in this case set to `PermissionRoleCode`.

**Comment by robbieaverill** [comment]
PR to add support for permission role codes at #26

**Comment by robbieaverill** [comment]
Fixed in #26
