### ISSUE TITLE
AuditHookSessionManagerTest can never run - checks against non-existent class name

### ISSUE THREAD

**Issue by LiamKearn** [silverstripe/silverstripe-auditor#55]
## Original reported issue
Looking at this commit of auditor: https://github.com/silverstripe/silverstripe-auditor/tree/3e7365cc746000762c08c292f140b2f46df20922

And it's CI job with silverstripe/session-manager installed: https://github.com/silverstripe/silverstripe-auditor/actions/runs/4878200297/jobs/8703966002

You can see in the above CI job that commit f31d851 of silverstripe/session-manager is being used.

https://github.com/silverstripe/silverstripe-session-manager/pull/39 [has changed](https://github.com/silverstripe/silverstripe-session-manager/blame/f31d851/src/Controllers/LoginSessionController.php#L35) the [`removeLoginSession`](https://github.com/silverstripe/silverstripe-auditor/pull/53/files#diff-88cde547e650cdb87cccb30f17652779e4290693fc7686092764c613c3f9edbaL52) to just `remove` yet this module is [still using `removeLoginSession`](https://github.com/silverstripe/silverstripe-auditor/blob/3e7365cc746000762c08c292f140b2f46df20922/tests/AuditHookSessionManagerTest.php#L52) even whilst the CI points at: [`^2`](https://github.com/silverstripe/silverstripe-auditor/blob/3e7365cc746000762c08c292f140b2f46df20922/.github/workflows/ci.yml#L17).

## Update
The FQCN for `LoginSessionController` that the `AuditHookSessionManagerTest` looks for is `SilverStripe\SessionManager\Control\LoginSessionController` - but the correct FQCN is `SilverStripe\SessionManager\Controllers\LoginSessionController`.

`AuditHookSessionManagerTest` specifically gets skipped on `if (!class_exists(LoginSessionController::class)) {` - and since that class _doesn't actually exist_ the test will never run.

`AuditHookSessionManagerTest` needs to use the correct FQCN for the `LoginSessionController` class, and then any outstanding problems with that test need to be fixed (e.g. calling the non-existent method mentioned in the original report).

Also check if this problem exists in the CMS 4 version of the module and target the PR as appropriate.

## PRs
- https://github.com/silverstripe/silverstripe-auditor/pull/74

**Comment by GuySartorelli** [comment]
PR merged, reassigned to Steve to double check the test now runs when session manager is installed

**Comment by emteknetnz** [comment]
Confirmed it now works as expected
