### ISSUE TITLE
Logging of failed logins & unknown users broken

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-auditor#63]
Currently a failed login attempt using an incorrect password (`authenticationFailed()`) always logs this warning:

> Could not determine username/email of failed authentication...

That happens because for standard non-LDAP logins it falls back to the posted `$data[Email::class]` which resolves to `$data['SilverStripe\Control\Email\Email']`. This should be just `$data['Email']` as per the `$_POST` request from the login form.

Secondly, there is currently no logging of failed login attempts due to an invalid email as this requires a `authenticationFailedUnknownUser()` extension method ([see source](https://github.com/silverstripe/silverstripe-framework/blob/5/src/Security/MemberAuthenticator/MemberAuthenticator.php#L193-L212)).

## PRs
- https://github.com/silverstripe/silverstripe-auditor/pull/62

**Comment by emteknetnz** [comment]
Linked PR has been merged, will be automatically tagged as 2.6.2 shortly
