### ISSUE TITLE
Clarify what AuditHookMemberGroupSet and AuditHookManyManyList are meant to do

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-auditor#65]
I've spent a bunch of time looking at https://github.com/silverstripe/silverstripe-auditor/issues/57 only to find out that there wasn't any problem.

Part of the problem was that I couldn't figure out what the intention of the code was. The point of this card is to not loose this hard won context.

## Acceptance criteria
- AuditHookMemberGroupSet and AuditHookManyManyList are covered by unit test
- There's some comments added to the classes.

## Pull request
- https://github.com/silverstripe/silverstripe-auditor/pull/66

**Comment by emteknetnz** [comment]
Linked PR has been merged
