### ISSUE TITLE
Remove auditor's dependecy on proxy-DB

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-auditor#73]
The CMS 6 version of auditor is still using a fork of tractorcow/silverstripe-proxy-db (silverstripe/silverstripe-proxy-db) because that's the only version that is CMS 6 compatible. Fork is archived though installable.

We need a CMS 6 compatible version of tractorcow/silverstripe-proxy-db on the tractorcow repository, and we also need to update the composer.json on auditor to use it.

## Acceptance criteria
- CMS 6 branch of auditor module does not dependend on proxy-db

## Multi PR CI run - contains CMS 6 framework + auditor PRs
- https://github.com/emteknetnz/silverstripe-installer/actions/runs/8871565407
- Note that the behat cms [failures](https://github.com/emteknetnz/silverstripe-installer/actions/runs/8871565407/job/24354734902#step:12:1220) are [existing](https://github.com/emteknetnz/silverstripe-installer/actions/runs/8872068299/job/24355920542#step:12:1220)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11209
- https://github.com/silverstripe/silverstripe-auditor/pull/75
- https://github.com/silverstripe/silverstripe-auditor/pull/76

**Comment by emteknetnz** [comment]
Looking at this again, I don't think the ACs are good. I don't think we want to remove the dependency on proxy-db, all that module does acts as connector module so that it'll add tractorcow/classproxy to the 'MySQLDatabase' so that silverstripe/auditor can add its extension hook so that database manipulations are logged.

We could put this functionality into auditor, but it's really does seem like the wrong place for this (though you could argue at a practical level that its not difference having it directly in auditor or in proxy-db which is a dependency of auditor).

The issue we're trying to solve here is that every couple of years we need to raise a PR to tractorcow/silverstripe-proxy-db to updating the dependency for silverstripe/framework to a high major version, and to get a new major versions of tractorcow/silverstripe-proxy-db tagged. Last time we did this for CMS 5 the turn around time didn't align with the release schedule of CMS 5 so we needed to release our own fork.

silverstripe-proxy-db really doesn't use that much API from silverstripe/framework. I think it's highly unlikely that we'll change the method signature of `SilverStripe\Core\Injector\Factory` any time soon, so I think it might make more sense to just raise a PR to tractorcow/silverstripe-proxy-db to allow `silverstripe/framework: ^5 || ^6` and call it a day

**Comment by michalkleiner** [comment]
Or could/should the proxy functionality be folded into framework?

**Comment by emteknetnz** [comment]
tractorcow/classproxy is independent from Silverstripe and can be used on an any PHP project, so that should be a separate dependency as it is now

proxy-db shouldn't be in framework IMO, as all it really is just a lightweight connector to add classproxy to what's instantiated by Injector when MySQLDatabase is created. If we put proxy-db into framework and had config to enable it, with the default being off, then we'd require a composer dependency in framework on classproxy which we shouldn't have IMO, because the auditor use case is pretty niche.

**Comment by emteknetnz** [comment]
Actually I had a think about this over the weekend and realised we should be able to easily get rid of proxy-db and simply use a good old extension hook to do the same thing. I've linked some PRs above.

**Comment by sabina-talipova** [comment]
All PRs have been merged. Task is completed.
